services:
  backend:
    build: ./backend
    container_name: coursetracker_backend
    restart: unless-stopped
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: database_conn_string_here
      NODE_ENV: "production"
    networks:
      - caddy_net
      - coursetracker_net

  frontend:
    build:
      context: ./frontend
    container_name: coursetracker_frontend
    restart: unless-stopped
    expose:
      - "8080"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - caddy_net
      - coursetracker_net

networks:
  coursetracker_net:
  caddy_net:
    external: true
